### ISSUE TITLE
`TupleVector` constructor based on `kwargs`

### ISSUE THREAD

**Issue by theogf** [cscherrer/TupleVectors.jl#19]
I realized I end up doing a lot of `TupleVector((; a=rand(10))` and was thinking it would nice and clean to have a constructor based on `kwargs...`:
```
TupleVector(;kwargs...) = TupleVector(NamedTuple(kwargs))
```

**Comment by cscherrer** [comment]
Good idea, PR welcome :)

**Comment by theogf** [comment]
Solved in #20
