### ISSUE TITLE
docs link is failing

### ISSUE THREAD

**Issue by bkamins** [cscherrer/TupleVectors.jl#27]
The problem is in README.md - both for stable and dev.

**Comment by cscherrer** [comment]
Thanks @bkamins . Sorry this isn't clear, but those links are placeholders from PkgTemplates.jl. Since the package is not very large, the docs are intended to be in the README. Do you see something missing in these?

I'll edit the README to remove the dead links.

**Comment by bkamins** [comment]
I think it is fine to just remove them as you did. Thank you! (I have added a reference to the package in the book)
