### ISSUE TITLE
Add support for Tables.jl interface?

### ISSUE THREAD

**Issue by oschulz** [cscherrer/TupleVectors.jl#28]
I would be really nice if TupleVectors would support the [Tables.jl](https://github.com/JuliaData/Tables.jl) interface, in the same fashion as [StructArrays.jl](https://github.com/JuliaArrays/StructArrays.jl) and [TypedTables.jl](https://github.com/JuliaData/TypedTables.jl)

**Comment by cscherrer** [comment]
This would be great. I've never done this before, ok to assign us both?

**Comment by oschulz** [comment]
Sure! We can use [ShapedAsNTArray](https://github.com/oschulz/ValueShapes.jl/blob/9065e8bbafef90e8fff55ad19868d8a1e456bec8/src/named_tuple_shape.jl#L528) as a template - the Tables.jl interface only need very few methods.

**Comment by cscherrer** [comment]
Not passing yet, but here's a start:
https://github.com/cscherrer/TupleVectors.jl/pull/29
